//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archimydes.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int UserStoryID { get; set; }
        public int UserId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Complexity { get; set; }
        public Nullable<System.DateTime> EstimatedTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
